-- =============================================================================
-- DEPRECATED — This file was a monolithic copy of V1–V5.
-- Use the individual seed files instead:
--   V1__seed_core.sql
--   V2__seed_isa.sql
--   V3__seed_contracts.sql
--   V4__seed_events.sql
--   V5__seed_revenue_wallets.sql
--
-- To deploy all seeds to Neon:
--   uv run db/migrations/deploy_seeds.py
-- =============================================================================
